version: '3.8'

services:
  nginx:
    # 移除 alpine，使用官方完整版 Nginx
    image: nginx
    container_name: ${CONTAINER_PREFIX}-nginx
    ports:
      - '${NGINX_HOST_PORT}:80'
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - api-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PHP_IMAGE_NAME}
    container_name: ${CONTAINER_PREFIX}-php
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/redis.ini:/usr/local/etc/php/conf.d/docker-php-ext-redis.custom.ini # redis 扩展配置

    depends_on:
      - mysql
      - redis
    networks:
      - api-network

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${CONTAINER_PREFIX}-mysql
    ports:
      - '${MYSQL_HOST_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - api-network

  # Redis 改用官方完整版，移除 alpine
  redis:
    image: redis
    container_name: ${CONTAINER_PREFIX}-redis
    ports:
      - '${REDIS_HOST_PORT}:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - api-network

networks:
  api-network:

volumes:
  mysql-data:
  redis-data:
