server {
    listen 80;
    index index.php;
    server_name localhost;

    # 你的项目根目录
    root /var/www/html;

    # 上传文件大小限制（与 php.ini 保持一致）
    client_max_body_size 20M;

    # 强制所有请求指向 index.php（API 专用）
    location / {
        try_files $uri /public/index.php$is_args$args;
    }

    # PHP 解析
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
